/**
 * One-off generator for a richer, real (non-30-day) example fixture.
 *
 * Uses the exact same real pipeline functions as apps/passport/app/api/analyze/route.ts
 * (fetchBlockscoutHistory -> normalizeAndDeduplicateBlockscoutItems -> computeDeterministicMetrics
 * -> evaluateCoverage -> createPassportBundle), just called with a wider, real observation
 * window than the app's default 30-day case. Does not modify packages/analysis or the live
 * app's default 30-day behavior — this is a standalone script producing a static real fixture.
 *
 * Subject: 0xc82f8B79Cd34bD98b1abEC72475F2a73Eb15CFA8 (the project's existing real example
 * wallet). Window chosen to capture exactly its real, publicly verifiable 100 most recent
 * successful outgoing transactions.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  validateEthereumAddress,
  fetchBlockscoutHistory,
  normalizeAndDeduplicateBlockscoutItems,
  computeDeterministicMetrics,
  evaluateCoverage
} from "@signal-passport/analysis";
import type { ObservationScope, PassportPayload } from "@signal-passport/schema";
import { createPassportBundle } from "@signal-passport/verification";

const SUBJECT = "0xc82f8B79Cd34bD98b1abEC72475F2a73Eb15CFA8";
const START_UTC = "2024-12-19T20:32:00.000Z";
const END_UTC = "2026-09-12T16:08:11.000Z"; // same frozen point-in-time as the standard example

async function main() {
  const validation = validateEthereumAddress(SUBJECT);
  if (!validation.isValid) throw new Error(`Invalid subject address: ${validation.error}`);
  const subjectAddress = validation.checksummed || validation.normalized || SUBJECT;
  const chainId = 1;

  const scope: ObservationScope = {
    subjectAddress,
    chainId,
    window: { startUtc: START_UTC, endUtc: END_UTC },
    direction: "outgoing",
    status: "ok"
  };

  console.log(`Fetching real Blockscout history for ${subjectAddress}...`);
  const historyResult = await fetchBlockscoutHistory(subjectAddress, { maxPages: 30 });
  console.log(`Fetched ${historyResult.items.length} raw items across ${historyResult.pageCount} pages (reachedEnd=${historyResult.reachedEnd}, hitPageLimit=${historyResult.hitPageLimit})`);

  const { qualifyingEvidence, totalEvaluated, qualifyingCount, duplicateCount } =
    normalizeAndDeduplicateBlockscoutItems(historyResult.items, {
      subjectAddress: scope.subjectAddress,
      chainId: scope.chainId,
      window: scope.window
    });
  console.log(`Qualifying: ${qualifyingCount} (of ${totalEvaluated} evaluated, ${duplicateCount} duplicates removed)`);

  const { claims } = computeDeterministicMetrics(qualifyingEvidence, scope);

  const coverage = evaluateCoverage({
    reachedEnd: historyResult.reachedEnd,
    hitPageLimit: historyResult.hitPageLimit,
    pageCount: historyResult.pageCount,
    totalRowsRetrieved: totalEvaluated,
    matchingRowsCount: qualifyingCount
  });
  console.log("Coverage:", coverage);

  const payload: PassportPayload = {
    passportId: `${chainId}:${subjectAddress.toLowerCase()}:1.0.0-extended`,
    subjectAddress,
    sourceChainId: chainId,
    snapshotVersion: "1.0.0",
    generationTimestamp: END_UTC,
    observationWindow: { startUtc: START_UTC, endUtc: END_UTC },
    coverage,
    claims,
    evidence: qualifyingEvidence,
    methodologyVersion: "1.0.0"
  };

  const bundle = createPassportBundle(payload, "1.0.0");

  const outPath = join(process.cwd(), "fixtures", "real", "passport-bundle-extended-100tx.json");
  writeFileSync(outPath, JSON.stringify(bundle, null, 2) + "\n");
  console.log(`\nWrote ${outPath}`);
  console.log(`Final observed_transaction_count claim value: ${claims.find(c => c.metricType === "observed_transaction_count")?.value}`);

  const metaPath = join(process.cwd(), "fixtures", "real", "passport-bundle-extended-100tx.metadata.json");
  writeFileSync(metaPath, JSON.stringify({
    description: "Real, unmodified Blockscout REST v2 data for the project's existing example wallet, retrieved with a wider real observation window than the app's default 30-day case, chosen to yield a richer demo dataset. Generated by scripts/generate-extended-fixture.ts using the same real pipeline functions as the live app.",
    subjectAddress,
    chainId,
    observationWindow: { startUtc: START_UTC, endUtc: END_UTC },
    retrievedAt: new Date().toISOString(),
    rawItemsFetched: historyResult.items.length,
    pageCount: historyResult.pageCount,
    qualifyingCount,
    duplicateCount,
    coverage
  }, null, 2) + "\n");
  console.log(`Wrote ${metaPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
